[llama]
api_key = "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"

[embed_model]
model_name = "jinaai/jina-embeddings-v2-base-en"

[qdrant]
url = "http://72.144.113.188:6333/"
collection_name = "user_collection"
